### ISSUE TITLE
Firmware dose not limit minus digits of axis

### ISSUE THREAD

**Issue by JamieKG** [houseofbugs/TH3D-Marlin#2]
### Bug Report
- Description: using CR10 S4 after homing the axis dont seam to be limited to 0 it can go into the minuses with out being limited 
- Expected behaviour: I would expect after homing the firmware to stop the steppers from going into minus digits
- Actual behaviour: it will go to minus what ever you turn it to
- Steps to reproduce:
  - home all axis 
  - the move one of the axis into a minus digit

[Config.zip](https://github.com/houseofbugs/TH3D-Marlin/files/1665246/Config.zip)

**Comment by JamieKG** [comment]
I've had a look and I think its missing
"#define MIN_SOFTWARE_ENDSTOPS"
on line 545

**Comment by houseofbugs** [comment]
This is intended and needed for Z offset setting. This is not a bug. Don't move your printer in a minus after homing.

**Comment by JamieKG** [comment]
ah I found the problem by mistake once you turn that know one to many times thats it you are trying to rip off your endstops
