### ISSUE TITLE
Manual Bed Leveling for Non-EZABL Setups

### ISSUE THREAD

**Issue by dwhacks** [houseofbugs/TH3D-Marlin#3]
"Manual Bed Leveling for Non-EZABL Setups" is listed as a feature yet I cannot find any way to enable this and test it. I know it exists in vanilla marlin. 

I have tried moving over some defines from the vanilla Marlin config file, and it compiled fine but I could not find the option, plus I still had my motion settings on the LCD which I believe shouldn't fit.

**Comment by houseofbugs** [comment]
The 4 point leveling assistant is enabled. Its accessible through the menu.
